Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from skimage import data, color, filters

# Load the sample 3D cell image
cells = data.cells3d()
image = cells[30, 1]  # Select one 2D slice from the 3D image
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mskimage[39;00m [38;5;28;01mimport[39;00m data, color, filters
[1;32m      5[0m [38;5;66;03m# Load the sample 3D cell image[39;00m
[0;32m----> 6[0m cells [38;5;241m=[39m [43mdata[49m[38;5;241;43m.[39;49m[43mcells3d[49m[43m([49m[43m)[49m
[1;32m      7[0m image [38;5;241m=[39m cells[[38;5;241m30[39m, [38;5;241m1[39m]  [38;5;66;03m# Select one 2D slice from the 3D image[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skimage/data/_fetchers.py:631[0m, in [0;36mcells3d[0;34m()[0m
[1;32m    605[0m [38;5;28;01mdef[39;00m [38;5;21mcells3d[39m():
[1;32m    606[0m [38;5;250m    [39m[38;5;124;03m"""3D fluorescence microscopy image of cells.[39;00m
[1;32m    607[0m 
[1;32m    608[0m [38;5;124;03m    The returned data is a 3D multichannel array with dimensions provided in[39;00m
[0;32m   (...)[0m
[1;32m    628[0m [38;5;124;03m        * After rescaling the voxel size is ``(0.29 0.26 0.26)``.[39;00m
[1;32m    629[0m [38;5;124;03m    """[39;00m
[0;32m--> 631[0m     [38;5;28;01mreturn[39;00m [43m_load[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mdata/cells3d.tif[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skimage/data/_fetchers.py:334[0m, in [0;36m_load[0;34m(f, as_gray)[0m
[1;32m    331[0m [38;5;66;03m# importing io is quite slow since it scans all the backends[39;00m
[1;32m    332[0m [38;5;66;03m# we lazy import it here[39;00m
[1;32m    333[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m [38;5;28;01mimport[39;00m imread
[0;32m--> 334[0m [38;5;28;01mreturn[39;00m imread([43m_fetch[49m[43m([49m[43mf[49m[43m)[49m, as_gray[38;5;241m=[39mas_gray)

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skimage/data/_fetchers.py:217[0m, in [0;36m_fetch[0;34m(data_filename)[0m
[1;32m    215[0m [38;5;28;01mif[39;00m _image_fetcher [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    216[0m     _skip_pytest_case_requiring_pooch(data_filename)
[0;32m--> 217[0m     [38;5;28;01mraise[39;00m [38;5;167;01mModuleNotFoundError[39;00m(
[1;32m    218[0m         [38;5;124m"[39m[38;5;124mThe requested file is part of the scikit-image distribution, [39m[38;5;124m"[39m
[1;32m    219[0m         [38;5;124m"[39m[38;5;124mbut requires the installation of an optional dependency, pooch. [39m[38;5;124m"[39m
[1;32m    220[0m         [38;5;124m"[39m[38;5;124mTo install pooch, use your preferred python package manager. [39m[38;5;124m"[39m
[1;32m    221[0m         [38;5;124m"[39m[38;5;124mFollow installation instruction found at [39m[38;5;124m"[39m
[1;32m    222[0m         [38;5;124m"[39m[38;5;124mhttps://scikit-image.org/docs/stable/install.html[39m[38;5;124m"[39m
[1;32m    223[0m     )
[1;32m    224[0m [38;5;66;03m# Download the data with pooch which caches it automatically[39;00m
[1;32m    225[0m _ensure_cache_dir(target_dir[38;5;241m=[39mcache_dir)

[0;31mModuleNotFoundError[0m: The requested file is part of the scikit-image distribution, but requires the installation of an optional dependency, pooch. To install pooch, use your preferred python package manager. Follow installation instruction found at https://scikit-image.org/docs/stable/install.html

